name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2

#       - uses: aws-actions/configure-aws-credentials@v1
#         with: 
#           aws-region: us-east-1
#           role-to-assume: my-github-actions-role

      - name: Find creds
        run: curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        
      - name: Run a one-line script
        run: echo hi

      - name: Run a multi-line script
        run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install awscli

      - name: aws cli
        run:  aws sts get-caller-identity
