name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-region: us-east-1

      - name: update
        run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install awscli

      - name: aws cli
        run:  aws sts get-caller-identity
